### ISSUE TITLE
Python modules can define more than one function

### ISSUE THREAD

**Issue by alchemyst** [DominicKafka/Quad8-FEM#1]
You currently seem to be using one .py file for each function in Matlab. This is completely superfluous in Python. The more idiomatic method would be to use a single module containing all of the functions.

**Comment by DominicKafka** [comment]
Good morning Mr. Sandrock

Oh ok!! Yes that makes sense, like many of the other modules.. So would you
recommend I put all the functions into one module, or is it even possible
to have them all in a separate part of the main mesher module? (I think
Delphi used to do something similar?)

Regards,
Dominic

**Comment by alchemyst** [comment]
I think the design that makes the most sense is to have a separate file for each of the executable entry points and one module for shared functions. Also, now that I’m talking about the “executable entry points” I think we should remove the reference to the year from quad4and8_ls_2013.m and perhaps consider names that say what the things do like “solve_fem.m” and “build_mesh.m”.

So, I would have three files: solve_fem.py, build_mesh.py to do their respective jobs and fem_utils.py to contain all the functions we use. You would then simply import fem_utils in the other files.

PS: I notice that you haven’t written any automated testing code yet. Please reconsider this decision - automated testing will make everything A LOT easier. We’ve reduced most of the .m code down to smaller parts that could be tested automatically quite easily. I CC Ms Inglis here so that you can contact her for help on getting the testing done.

On 25 Mar 2014, at 7:55 , DominicKafka notifications@github.com wrote:

> Good morning Mr. Sandrock
> 
> Oh ok!! Yes that makes sense, like many of the other modules.. So would you
> recommend I put all the functions into one module, or is it even possible
> to have them all in a separate part of the main mesher module? (I think
> Delphi used to do something similar?)
> 
> Regards,
> Dominic
> 
> On Mon, Mar 24, 2014 at 9:36 PM, Carl Sandrock notifications@github.comwrote:
> 
> > You currently seem to be using one .py file for each function in Matlab.
> > This is completely superfluous in Python. The more idiomatic method would
> > be to use a single module containing all of the functions.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHubhttps://github.com/DominicKafka/Quad8-FEM/issues/1
> > .
> > 
> > —
> > Reply to this email directly or view it on GitHub.

__
,------------http://www.up.ac.za/chemeng/csandrock-------------.
|                                                     N-CH3    |
|  ,---.,----.   Carl Sandrock                       / \       |
| / ,--'| ---<   MEng (Control), PrEng    +     N---C   C=O    |
| \ `----`--  )  University of Pretoria    +    "   "   |      |
|  `~-------~`   carl.sandrock@up.ac.za  +++   CH   C   N-CH3  |
|                                                \ / \ /       |
| Brought to you by the miracle of Caffeine   3HC-N   C=O      |
`--------------------------------------------------------------`

**Comment by DominicKafka** [comment]
Good afternoon Mr. Sandrock

Thank you for the valuable feedback! Yes, I understand the file structure
you are proposing and I think that will work well. I also agree with
regards to the name changes. I will talk to Prof. Kok tomorrow. He may want
a reference to quad8 (or something of the sort) to remain, so I will just
double check with him.

With regards to testing code, I have played with small code that inputs
constants for both the separated .m and the .py files and compared answers
of both files. If there was a difference, I would revise the .py code until
they gave identical answers. How best would an automated code checking
script work in theory?

Regards
Dominic
