### ISSUE TITLE
Conform to PEP8

### ISSUE THREAD

**Issue by alchemyst** [DominicKafka/Quad8-FEM#2]
There is a standard for how Python code should be formatted, called [PEP 8](http://legacy.python.org/dev/peps/pep-0008/). There are [tools](https://pypi.python.org/pypi/pep8) that check your code for compliance to this standard. The current code does not comply with these standards. Fix this stuff before the code becomes too big, and run the checker periodically as you add more code. Depending on the editor you use, you may be able to incorporate these checks in the editor live. Try to enable the pep8 support in your editor. If you don't use an editor which supports this, consider switching.

**Comment by DominicKafka** [comment]
Good Day Mr. Sandrock

I tried to make my previous editor PEP8 compatible, but for some reason the
function (although existing) was blocked out, so I have switched to
Ninja-IDE instead, which seems to have the needed functionality.

Regards,
Dominic
