### ISSUE TITLE
Reduce the number of arguments to functions

### ISSUE THREAD

**Issue by alchemyst** [DominicKafka/Quad8-FEM#4]
The functions in both of the language versions are at the moment passing more arguments than they could. Specifically, the sizes of things travel with them, so we shouldn't need to pass out things like `nnodes` when we have a list of nodes with a length to look at. I recommend taking these out of both codes.

**Comment by DominicKafka** [comment]
Oh I see what you mean, one can then read the length on the receiving side
of the code and work with the values from there. I will look into that!
